### ISSUE TITLE
긴급 이슈

### ISSUE THREAD

**Issue by seruid** [Jaysok/kosta179-final-wisely-food-life#9]
testMemberController 에서 사장회원 가입시 null pointer 에러 발생

@Test
	public void testRegisterFoodie() throws Exception {
		String url = "/registerFoodie.do";
		//RequestBuilder에 url과 request parameter를 셋팅해줌
		RequestBuilder rb = post(url)
				.param("name",fvo.getName() )
				.param("address", fvo.getAddress() )
				.param("tel",fvo.getTel() )
				.param("openTime",fvo.getOpenTime() )
				.param("closeTime", fvo.getCloseTime() )
				.param("intro",fvo.getIntro())
				.param("latitude", new Double(fvo.getLatitude()).toString())
				.param("longtitude", new Double(fvo.getLongtitude()).toString())
				.param("bookableTableCount",new Double(fvo.getBookableTableCount()).toString())
				.session(session);
				
				this.result = this.mockMvc.perform(rb).andDo(print()).andReturn();
		
				// ModelAndView를 받아옴
				ModelAndView mv = this.result.getModelAndView();
				**Map<String, Object> model = mv.getModel();**
				
				//model에 셋팅된 값이 mvo와 같은지 테스트함
				FoodieVO fvo = (FoodieVO) model.get("fvo");

				System.out.println("foodieNo  " + fvo.getFoodieNo());
				FoodieVO registerFVO = foodieDAO.selectFoodie(fvo.getFoodieNo());
				System.out.println("***************************\n"+fvo +"\n" + registerFVO);
				//assertEquals(fvo, registerFVO);
				//viewName이 redirect:home.do와 같아야함
				String viewName = mv.getViewName();
				assertEquals(String.format("redirect:home.do"),viewName);
				
				//Request Method 가 POST인지 검증
				assertEquals(RequestMethod.POST.toString(), this.result.getRequest().getMethod());
			}

위가 test 코드. 위 테스트 코드중 볼드친 부분
**Map<String, Object> model = mv.getModel();**
만 거치면 계속 Null pointer 발생

아래는 jUnit 상 error code

java.lang.NullPointerException
	at org.kosta.tacto.member.TestMemberController.testRegisterFoodie(TestMemberController.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by yunheenet** [comment]
Map<String, Object> model = mv.getModel();  다음줄에
FoodieVO registerFVO = foodieDAO.selectFoodie(fvo.getFoodieNo()); 가 실행되는데

컨트롤러 단계에서 param으로 받은 값들로 
int resultFoodieNo = FoodieSeriveLogic.registerFoodie(FoodieVO foodieVO);
이런식의 호출이 이루어 지고 foodieNo를 model attribute로 설정해줘야 할듯합니다.

지금의 코드상으로는 FoodieVO registerFVO = foodieDAO.selectFoodie(fvo.getFoodieNo()); 에서
fvo.getFoodieNo가 foodieNo을 가지고 있지 않을 확률이 높아보입니다 ㅠㅠ

**Comment by Jaysok** [comment]
1. foodieVO의 bookableTableCount의 타입이 안 맞아서 생기는 에러가 있습니다.
`.param("bookableTableCount",new Double(fvo.getBookableTableCount()).toString())`이 부분을
`.param("bookableTableCount",((Integer)fvo.getBookableTableCount()).toString())` 이렇게 고쳐주세요.

2. session에 mvo가 셋팅이 안 되서 NullPointerException이 뜨는 것 같습니다.
RequestBuilder객체를 만들기 전에 `session.setAttribute(mvo)`로 멤버 객체를 셋팅해주세요.

그러면 아래와 같이 에러가 바뀔 겁니다.
```java
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.kosta.tacto.foodie.service.FoodieServiceLogicException: SYS : email, bno 누락
(이하 생략)
```

**Comment by seruid** [comment]
세션에 mvo 와 svo 즉 멤버와 사장도 심어서 console 에 출력도 되는거 확인해 봤는데
재석이가 올려준 에러가 계속해서 일어남.  내일 오전 회의에서 이슈토론이 필요해 보임

**Comment by seruid** [comment]
모든 이슈 클리어됨
